name: om2_ps_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconda::bedtools=2.31.1
  - bioconda::bowtie2=2.5.4
  - bioconda::kmer-jellyfish=2.3.1
  - conda-forge::python=3.10
  - conda-forge::uv=0.9.5
  - bioconda::samtools=1.23
  - bioconda::sam2pairwise=1.0.0 # TODO remove once om2 workflow is fully integrated 
  - pybedtools=0.12.0
  # - snakemake=5.20.1
  - snakemake=7
  - xgboost=2.1.1
  - pip
  - pip:
    - git+ssh://git@github.com/beliveau-lab/OligoMiner2.git
